# Generated by Django 2.1 on 2018-12-05 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id_Developer', models.AutoField(primary_key=True, serialize=False, verbose_name='id Usuario')),
                ('id_DevTeam', models.IntegerField(null=True, verbose_name='Id Team')),
                ('DevName', models.CharField(max_length=250, null=True, verbose_name='Nombre')),
                ('Email', models.EmailField(max_length=254, null=True, verbose_name='Correo')),
                ('BirthDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Cumple Años')),
                ('Password', models.CharField(max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Programador',
                'verbose_name_plural': 'Programadores',
            },
        ),
        migrations.CreateModel(
            name='DevTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Nombre del equipo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('idDev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id del Programador')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Equipo-Programador',
                'verbose_name_plural': 'Equipos-Programadores',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id_Team', models.AutoField(primary_key=True, serialize=False, verbose_name='id del equipo')),
                ('TeamName', models.CharField(max_length=250, null=True, verbose_name='Nombre del equipo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.AddField(
            model_name='devteam',
            name='idTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Developer.Team', verbose_name='Id del Equipo'),
        ),
    ]
